### ISSUE TITLE
Error when running "npm run dist:win": AzureSignTool.exe not found

### ISSUE THREAD

**Issue by SamBouwer** [anyproto/anytype-ts#156]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When I follow the steps to build anytype-ts from source, I run into the following error when running the `npm run dist:win` step:

```
webpack 5.88.2 compiled with 3 warnings in 42641 ms
  • electron-builder  version=24.6.3 os=5.15.0-78-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
[BeforeBuild] platform: windows arch: x64
[BeforeBuild] folder:
  • packaging       platform=win32 arch=x64 electron=22.0.0 appOutDir=dist/win-unpacked
{
  path: '/home/bouwers/any-docker/anytype-clients/anytype-ts/dist/win-unpacked/Anytype.exe',
  name: 'Anytype',
  site: 'https://anytype.io',
  options: {
    sign: './electron/hook/sign.js',
    target: 'nsis',
    icon: 'electron/img/icon256x256.png',
    publish: [ [Object] ]
  },
  hash: 'sha1',
  isNest: false,
  computeSignToolArgs: [Function: computeSignToolArgs]
}
Error:  Error: Command failed: AzureSignTool.exe sign -du "https://anytype.io" -fd sha384 -td sha384 -tr http://timestamp.digicert.com --azure-key-vault-url "undefined" --azure-key-vault-client-id "undefined" --azure-key-vault-tenant-id "undefined" --azure-key-vault-client-secret "undefined" --azure-key-vault-certificate "undefined" -v "/home/bouwers/any-docker/anytype-clients/anytype-ts/dist/win-unpacked/Anytype.exe"
/bin/sh: 1: AzureSignTool.exe: not found

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'AzureSignTool.exe sign -du "https://anytype.io" -fd sha384 -td sha384 -tr http://timestamp.digicert.com --azure-key-vault-url "undefined" --azure-key-vault-client-id "undefined" --azure-key-vault-tenant-id "undefined" --azure-key-vault-client-secret "undefined" --azure-key-vault-certificate "undefined" -v "/home/bouwers/any-docker/anytype-clients/anytype-ts/dist/win-unpacked/Anytype.exe"'
} /bin/sh: 1: AzureSignTool.exe: not found

  ⨯ Command failed: AzureSignTool.exe sign -du "https://anytype.io" -fd sha384 -td sha384 -tr http://timestamp.digicert.com --azure-key-vault-url "undefined" --azure-key-vault-client-id "undefined" --azure-key-vault-tenant-id "undefined" --azure-key-vault-client-secret "undefined" --azure-key-vault-certificate "undefined" -v "/home/bouwers/any-docker/anytype-clients/anytype-ts/dist/win-unpacked/Anytype.exe"
/bin/sh: 1: AzureSignTool.exe: not found
  failedTask=build stackTrace=Error: Command failed: AzureSignTool.exe sign -du "https://anytype.io" -fd sha384 -td sha384 -tr http://timestamp.digicert.com --azure-key-vault-url "undefined" --azure-key-vault-client-id "undefined" --azure-key-vault-tenant-id "undefined" --azure-key-vault-client-secret "undefined" --azure-key-vault-certificate "undefined" -v "/home/bouwers/any-docker/anytype-clients/anytype-ts/dist/win-unpacked/Anytype.exe"
/bin/sh: 1: AzureSignTool.exe: not found


                                                                                                                                                    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at WinPackager.signApp (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/winPackager.ts:384:27)
    at WinPackager.doSignAfterPack (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/platformPackager.ts:332:32)
    at WinPackager.doPack (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/platformPackager.ts:317:7)
    at WinPackager.pack (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/packager.ts:442:9)
    at executeFinally (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/home/bouwers/any-docker/anytype-clients/anytype-ts/node_modules/builder-util/src/promise.ts:12:14)
```

### Expected Behavior

The build to complete successfully, or gracefully inform the user that this tool is missing (and for bonus points: instruct the user how to install it).

### Steps To Reproduce

1. Follow the instructions as written in the README.md file in this repository,
2. At some point, you need to `run npm run dist:win`,
3. Get the error as posted in this bug report.

### Environment

```markdown
- OS: Linux Ubuntu
- Version: 22.04.2 LTS (GNU/Linux 5.15.0-78-generic x86_64)
```

**Comment by ra3orblade** [comment]
Yeah, unfortunately now it won't work out of the box, so either run it as a local server or wait for me to fix the hook, the hook should be only run on CI as even if you install sign tool you wont have the certificate.

**Comment by ra3orblade** [comment]
Another way is to remove `line 519: "sign": "./electron/hook/sign.js", ` from package.json

**Comment by SamBouwer** [comment]
I've scripted to remove the line mentioned by Razor, so closing issue.
